FROM php:8.1.1-fpm-alpine3.15

RUN docker-php-ext-install pdo pdo_mysql
RUN apk add libzip-dev
RUN docker-php-ext-install zip

RUN curl -sS https://getcomposer.org/installer | php  -- --install-dir=/usr/local/bin --filename=composer

RUN chown -R www-data:www-data /var/www
